---
# This Playbook runs all the common plays in the deployment

- name: Create the hosts file for all machines
  template: src=hosts.j2 dest=/etc/hosts

- name: Create the repository for Mongo
  copy: src=mongo.repo.j2 dest=/etc/yum.repos.d/mongo.repo

- name: Create the EPEL Repository.
  copy: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg

- name: Create SELinux Policy
  copy: src=mongodb_cgroup_memory.te dest:

- name: Create the mongod user
  user: name=mongod comment="MongoD"

- name: Install the mongodb package
  yum: 
    name:
      - mongodb-org
      - checkpolicy
    state: present

- name: Update SELinux Policies
  shell:
    cmd: checkmodule -M -m -o mongodb_cgroup_memory.mod mongodb_cgroup_memory.te /
         semodule_package -o mongodb_cgroup_memory.pp -m mongodb_cgroup_memory.mod /
         sudo semodule -i mongodb_cgroup_memory.pp
    chdir: 
